### ISSUE TITLE
Can't seem to get second video to start

### ISSUE THREAD

**Issue by Ceorl64** [Blazored/Video#10]
I'm using the example code, except I've added a parameter for the video file name.  My Navmenu contains a list of file names to select from.  The first file starts up without issue, but if I select a second, it never starts.  I can restart the code, and select any video file name from my list, and it always starts up, so I know it's able to find all the files, but anytime I select a subsequent video, it never starts.  When I include a breakpoint, I can see the file name:

![image](https://user-images.githubusercontent.com/46032725/120501370-2db88200-c387-11eb-9a38-7fc37c45e315.png)

After selecting the second video, again, I can see the new video file name at the breakpoint, but it never get loaded and played.
![image](https://user-images.githubusercontent.com/46032725/120501907-9acc1780-c387-11eb-8afb-610b87e0eabd.png)

Keep in mind, I can always play the second video first without issue, but never another behind it.

Is there a way to force the next video to load?

**Comment by AmirMahdiNassiri** [comment]
I'm facing the same issue but I didn't add a parameter for video file name and I change the source according to my ViewModel changes such as this:

```
<BlazoredVideo>
	<source src="@ViewModel.VideoSource" type="video/mp4" />
</BlazoredVideo>
```

I can verify that the source gets updated successfully by Blazor, but the new video is not loaded.

**Comment by SQL-MisterMagoo** [comment]
Hi - you can force a reload by using a `@key` like this:

```html
<BlazoredVideo @key=videos[selectedVideo]>
	<source src=@videos[selectedVideo] type="video/mp4" />
</BlazoredVideo>
<button @onclick=NextVideo>Next Video</button>
```

In this code, I have an array of videos and the current index is held in `selectedVideo (int)` 
I make the `@key` the same as the video URL, so when the URL changes, Blazor will recreate the `video` element.
The method `NextVideo` just increments `selectedVideo` and wraps back round to zero at the end of the video list.

**Comment by Budsy** [comment]
> Hi - you can force a reload by using a `@key` like this:
> 
> ```
> <BlazoredVideo @key=videos[selectedVideo]>
> 	<source src=@videos[selectedVideo] type="video/mp4" />
> </BlazoredVideo>
> <button @onclick=NextVideo>Next Video</button>
> ```
I also can only make the first video on the page render and play. It works well. But subsequent videos will not render completely. I used this technique and it briefly flashes the black video frame, but it disappears, leaving an audio player gadget showing. It plays the audio track nicely, but no video.

**Comment by gregoryagu** [comment]
This worked for me to load a video dynamically:
```
<BlazoredVideo @key="@ProfileVideoUrl" class="w-100"
               style="max-width:800px;"
               controls="controls">
    <source src="@ProfileVideoUrl" type="video/mp4" />
</BlazoredVideo>
```
