### ISSUE TITLE
Can we control Video from code?

### ISSUE THREAD

**Issue by mimranfaruqi** [Blazored/Video#11]
I certainly want to control video as if I would do with JavaScript. When I want to pause and when I want to replay the video from the same time or from a different time. How do I control that? Can I use anything with @ref?

Thank you for amazing library though :)

**Comment by quintonv** [comment]
Hi, did you solve this? I also need to play from code and don't see any options for this

**Comment by mimranfaruqi** [comment]
> Hi, did you solve this? I also need to play from code and don't see any options for this

No really. Using JavaScript Interop to pause and play video :(

**Comment by SQL-MisterMagoo** [comment]
Will be addressed by PR #4
