### ISSUE TITLE
Autplay

### ISSUE THREAD

**Issue by michalss** [Blazored/Video#12]
Hi is there some example how to do autoplay just after page is rendered  in Blazor Server?

**Comment by michalss** [comment]
i did try 
		 autoplay="autoplay" 
		 loop="loop"

But is simply not start

**Comment by SQL-MisterMagoo** [comment]
You can try adding "muted" to the attributes, but even then it is not guaranteed to autoplay. 
Browsers are in control of things like this and they can all handle it differently.

**Comment by pietsoftwaretogo** [comment]
Quick and dirty solution.

I've added the following javascript to my index.html
```html
    <script>
        function autoPlay(id)
        {
            document.getElementById(id).play();
        }
    </script>
```

In the BlazoredVideo.LoadedData event i call the javascript using:

```html
        <BlazoredVideo
                id="myId"
                muted="muted"
                autoplay="autoplay" LoadedData="LoadedData">
            <source src="@path" type="video/mp4" />
        </BlazoredVideo>
```

```c#
    private void LoadedData(VideoState state)
    {
        JS.InvokeVoidAsync("autoPlay", "myId");
    }
```

You need to inject the IJSRuntime at the top of the page like:
`@inject IJSRuntime JS`

>*Note*, you do need to have some interaction with the browser in order for it to play automatically. Or else you will see this error in Chrome's console: `Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first.` See: https://developer.chrome.com/blog/autoplay/

**Comment by pieteckhart** [comment]
This seems to work:

# index.html
```html
    <script>
        function autoPlay(id)
        {
            document.getElementById(id).play();
        }
    </script>
```
# index.razor
`@inject IJSRuntime JS`

```html
<BlazoredVideo
            id="myId"
            muted="muted"
            autoplay="autoplay"
            LoadedData="LoadedData">
        <source src="@path" type="video/mp4" />
</BlazoredVideo>
```

```C#
    private void LoadedData(VideoState state)
    {
        JS.InvokeVoidAsync("autoPlay", "gource");
    }
```

>Just make sure you interact with the page first (by clicking somewhere for example). Or else you get `Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first.`
