### ISSUE TITLE
Can I use the repo to view some videos via proxy?

### ISSUE THREAD

**Issue by zydjohnHotmail** [Blazored/Video#13]
Hello:
Due to some location restrication, I have to use a proxy to view some videos (I think the video format is MP4) hosted on some web site.
Let me know if I can set up proxy, like the C# httpclient has built-in support for using proxy to view some videos?
By the way, it it not easy to know the video URL beforehand, I can use some program to detect the video URL from some website, therefore, I want to know if I can save the detected video URL in a text file, so the repo can open the text file to know which video URLs to play.
Thanks,

**Comment by SQL-MisterMagoo** [comment]
This component has nothing to do with proxies
