### ISSUE TITLE
[Feature Request] Width / Height

### ISSUE THREAD

**Issue by AlexHedley** [Blazored/Video#37]
Would it be possible to expose the `width` and `height` properties?

> [height](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#height)  
> The height of the video's display area, in [CSS pixels](https://drafts.csswg.org/css-values/#px) (absolute values only; [no percentages](https://html.spec.whatwg.org/multipage/embedded-content.html#dimension-attributes)).

> [width](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#width)  
> The width of the video's display area, in [CSS pixels](https://drafts.csswg.org/css-values/#px) (absolute values only; [no percentages](https://html.spec.whatwg.org/multipage/embedded-content.html#dimension-attributes)).

- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video

## Example

```html
<video controls width="250" height="100">
  <source src="/media/cc0-videos/flower.webm" type="video/webm" />
</video>
```

---

Also is there a possibility to `.requestFullscreen()`

- https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullscreen

**Comment by AlexHedley** [comment]
@SQL-MisterMagoo thanks for adding `requestFullscreen` :-)

**Comment by AlexHedley** [comment]
@SQL-MisterMagoo are you able to create a **Release** please?

**Comment by AlexHedley** [comment]
@chrissainty could you create a release please?

**Comment by SQL-MisterMagoo** [comment]
@AlexHedley cool it - you don't dictate when releases happen.

**Comment by AlexHedley** [comment]
Apologies, my enthusiasm got the better of me.
I thought you might have been busy when you hadn’t replied.

**Comment by cpajchambers** [comment]
+1 for a new release, please.
